config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  resources :recipes
  resources :shopping_list_items, only: [ :create, :destroy, :index ]

  root "recipes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :recipe_ingredients, dependent: :destroy
  accepts_nested_attributes_for :recipe_ingredients, allow_destroy: true

  belongs_to :user

  validates :name, :instructions, :prep_time, :cooking_time, :serves, presence: true
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe

  validates :quantity, :unit, presence: true
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/shopping_list_item.rb
class ShoppingListItem < ApplicationRecord
  belongs_to :user
  belongs_to :recipe_ingredient
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy

  has_many :recipes, dependent: :destroy
  has_many :shopping_list_items

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end

    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id]) if cookies.signed[:session_id]
    end

    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_path
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end

    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_path, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Current.user.recipes.new(recipe_params)

    if @recipe.save
      redirect_to @recipe
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])

   if @recipe.update(recipe_params)
      redirect_to @recipe
   else
      render :edit, status: :unprocessable_entity
   end
  end

  def destroy
    @recipe = Recipe.find(params[:id])

    @recipe.destroy
    redirect_to recipes_path
  end

  private
  def recipe_params
    params.expect(recipe: [ :name, :instructions, :prep_time, :cooking_time, :serves, :is_gluten_free, :is_dairy_free, :is_vegetarian, :is_vegan,
      recipe_ingredients_attributes: [ [ :_destroy, :quantity, :unit, :name, :notes, :id ] ] ])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_path
  end
end

app/controllers/shopping_list_items_controller.rb
class ShoppingListItemsController < ApplicationController
  def index
    @shopping_list_items = ShoppingListItem.where(user: Current.user)
  end

  def create
    @shopping_list_item = Current.user.shopping_list_items.new(shopping_list_item_params)

    if @shopping_list_item.save
      flash[:notice] = "Successfully added to shopping list"
    else
      flash[:error] = "Unable to add to shopping list"
    end
    redirect_back fallback_location: root_path
  end

  def destroy
    @shopping_list_item = ShoppingListItem.find(params[:id])

    @shopping_list_item.destroy
    redirect_to shopping_list_items_path
  end

  private
  def shopping_list_item_params
    params.expect(shopping_list_item: [ :recipe_ingredient_id ])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shopping_list_items_helper.rb
module ShoppingListItemsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-primary">
    <div class="container">
        <%= link_to root_path do %>
            <%= image_tag "icon.png", class: "navbar-brand p-0", alt: "Recipes", style: "height: 50px; width: auto;" %>
        <% end %>
        <div class="d-inline-flex align-items-center">
            <% if authenticated? %>
                <div class="nav-item">
                    <%= link_to "Shopping list", shopping_list_items_path, class: "nav-link me-3 text-white" %>
                </div>
                <div class="nav-item">
                    <%= button_to "Sign out", session_path, method: :delete, class: "btn btn-secondary text-white" %>
                </div>
            <% else %>
                <%= button_to "Sign in", new_session_path, class: "btn btn-secondary text-white" %>
            <% end %>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Meal Planner Rails" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <%# <link rel="icon" href="/icon.svg" type="image/svg+xml"> %>
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-primary">
    <%= render "layouts/navbar" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_with model: recipe, data: {controller: "nested-fields"} do |form| %>
    <div>
        <%= form.label :name %>
        <%= form.text_field :name %>
    </div>

    <div>
        <%= form.label :prep_time %>
        <%= form.text_field :prep_time %>
    </div>

    <div>
        <%= form.label :cooking_time %>
        <%= form.text_field :cooking_time %>
    </div>

    <div>
        <%= form.label :serves %>
        <%= form.text_field :serves %>
    </div>

    <div>
        <%= form.label :is_gluten_free %>
        <%= form.checkbox :is_gluten_free %>
    </div>

    <div>
        <%= form.label :is_dairy_free %>
        <%= form.checkbox :is_dairy_free %>
    </div>

    <div>
        <%= form.label :is_vegetarian %>
        <%= form.checkbox :is_vegetarian %>
    </div>

    <div>
        <%= form.label :is_vegan %>
        <%= form.checkbox :is_vegan %>
    </div>

    <%= yield form %>

    <div data-nested-fields-target="fields"></div>
    <div>
        <%= button_tag "Add ingredient", type: :button, data: { action: "nested-fields#append" } %>

        <template data-nested-fields-target="template">
            <%= fields_for "recipe[recipe_ingredients_attributes][]", RecipeIngredient.new, index: "__INDEX__" do |recipe_ingredients_form| %>
                <%= render "recipe_ingredient_fields", form: recipe_ingredients_form %>
            <% end %>
        </template>
    </div>

    <div>
        <%= form.label :instructions %>
        <%= form.text_area :instructions %>
    </div>

    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/recipes/_recipe_ingredient_fields.html.erb
<div data-nested-fields-target="wrapper" data-controller="nested-fields">
    <%= form.hidden_field :_destroy, data: { nested_fields_target: "destroyField" } %>

    <%= form.label :name %>
    <%= form.text_field :name %>

    <%= form.label :quantity %>
    <%= form.text_field :quantity %>

    <%= form.label :unit %>
    <%= form.text_field :unit %>

    <%= form.label :notes %>
    <%= form.text_field :notes %>

    <%= button_tag "Remove ingredient", type: :button, data: {action: "nested-fields#remove"} %>
</div>

app/views/recipes/edit.html.erb
<%= link_to "Back", recipe_path(@recipe) %>
<%= render "form", recipe: @recipe do |form| %>
    <%= form.fields_for :recipe_ingredients do |recipe_ingredients_form| %>
        <%= render "recipe_ingredient_fields", form: recipe_ingredients_form %>
    <% end %>
<% end %>

app/views/recipes/index.html.erb
<div data-controller="search-recipes">
    <div class="container">
        <div class="row row-cols-auto my-3 align-items-center">
            <div class="col-3">
                <%= link_to "New recipe", new_recipe_path, class: "btn btn-primary text-white" %>
            </div>  
            <div class="col-4">
                <%= search_field_tag "search", nil, placeholder: "Find a recipe", class: "form-control form-control-lg text-white", style: "background-color: #7E927B; border: none" , data: { action: "search-recipes#filter", search_recipes_target: "search" } %>
            </div>
        </div>
    </div>

    <div class="row row-cols-4 gy-3">
        <% @recipes.each do |recipe| %>
            <div class="col" data-search-recipes-target="recipe">
                <div class="card">
                    <div class="card-body">
                        <p><%= link_to recipe.name, recipe %></p>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/recipes/new.html.erb
<%= link_to "Back", root_path %>

<%= render "form", recipe: @recipe %>

app/views/recipes/show.html.erb
<%= link_to "Back", root_path %>

<% flash.each do |type, msg| %>
    <div class="alert alert-success" data-controller="remove-flash" data-remove-flash-target="flash">
        <%= msg %>
    </div> 
<% end %>

<h1><%= @recipe.name %></h1>
<p>Prep time: <%= @recipe.prep_time %></p>
<p>Cooking time: <%= @recipe.cooking_time %></p>
<p>Serves: <%= @recipe.serves %></p>
<% @recipe.recipe_ingredients.each do |recipe_ingredient| %>
    <p><%= recipe_ingredient.name %>, <%= recipe_ingredient.quantity %> <%= recipe_ingredient.unit %> <%= recipe_ingredient.notes %></p>
    <%= button_to "Add to shopping list", shopping_list_items_path, method: :post, params: { shopping_list_item: { recipe_ingredient_id: recipe_ingredient.id } } %>
<% end %>
<p><%= @recipe.instructions %></p>

<%= link_to "Edit", edit_recipe_path(@recipe) %>
<%= button_to "Delete recipe", @recipe, method: :delete, data: { turbo_confirm: "Are you sure?" } %>

app/views/shopping_list_items/index.html.erb
<ul>
    <% @shopping_list_items.each do |shopping_list_item| %>
        <li>
            <%= shopping_list_item.recipe_ingredient.name %>
            <%= button_to "Remove", shopping_list_item, method: :delete %>
        </li>
    <% end %>
</ul>